BasicBrowser/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^topic/(?P<topic_id>\d+)/$', 'tmv_app.views.topic_detail'),
    (r'^term/(?P<term_id>\d+)/$', 'tmv_app.views.term_detail'),
    (r'^doc/(?P<doc_id>\d+)/$', 'tmv_app.views.doc_detail'),
    (r'^topic_list$', 'tmv_app.views.topic_list_detail'),
    (r'^topic_presence$', 'tmv_app.views.topic_presence_detail'),
    (r'^stats$', 'tmv_app.views.stats'),
    (r'^settings$', 'tmv_app.views.settings'),
    (r'^settings/apply$', 'tmv_app.views.apply_settings'),
    (r'^topic/random$', 'tmv_app.views.topic_random'),
    (r'^doc/random$', 'tmv_app.views.doc_random'),
    (r'^term/random$', 'tmv_app.views.term_random'),
    # Example:
    # (r'^BasicBrowser/', include('BasicBrowser.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)


#onyl serve static content for development
urlpatterns += patterns('', (
r'^static/(?P<path>.*)$',
'django.views.static.serve',
{'document_root': 'static'}
))

BasicBrowser/tmv_app/models.py
from django.db import models

class Topic(models.Model):
    title = models.CharField(max_length=50)

    def __unicode__(self):
        return str(self.title)

class Term(models.Model):    
    title = models.CharField(max_length=50)

class TopicTerm(models.Model):
    topic = models.IntegerField()
    term = models.IntegerField()
    score = models.FloatField()

class Doc(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    
    def word_count(self):
        return len(str(self.content).split())

class DocTopic(models.Model):
    doc = models.IntegerField()
    topic = models.IntegerField()
    score = models.FloatField()
    scaled_score = models.FloatField()

class DocTerm(models.Model):
    doc = models.IntegerField()
    term = models.IntegerField()
    score = models.FloatField()

class RunStats(models.Model):
    start = models.DateTimeField()
    batch_count = models.IntegerField()
    last_update = models.DateTimeField()
    topic_titles_current = models.BooleanField()

class Settings(models.Model):
    doc_topic_score_threshold = models.FloatField()
    doc_topic_scaled_score = models.BooleanField()

BasicBrowser/templates/doc.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/pie.js"></script>
    <script language="JavaScript" src="/static/js/search.js"></script>


    <script type="text/JavaScript">
    <!--

    var array = {{ pie_array|safe }};
    var elements = generate_pie_elements(array);
    var piec = null;
    function init() {
        // create pie chart
        piec = new PieChart(elements);
        piec.initialize();

    }

    function highlight(i) {
        piec.highlight(i);
    }
    
    function unhighlight() {
        piec.unhighlight();
    }
    //-->
    </script>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <title>{{ doc.title }}</title>

    <link href="/static/css/styling.css" rel="stylesheet" type="text/css">
</head>

<body onLoad="init()">
{{ nav_bar|safe }}

    <div id="top"></div>

    <h1 id="header">
        <table><tr>
            <td id="title">{{ doc.title }}</td>
        </tr></table>

        <hr noshade>
    </h1>

    <div id="main">
        <table><tr>
            <td width="210px">
                <table class="dark">
                <tr><td><canvas id="canvas" width="200" height="200"></canvas></td></tr>
                <tr class="title">
                    <td>related topics</td>
                </tr>
                {% if topics %}
			{% for topic in topics %}
			<tr class="list"><td id="topic_{{ topic.id }}" onmouseover="highlight({{ forloop.counter|add:"-1" }})" onmouseout="unhighlight()" onclick="window.location.href='/topic/{{ topic.id }}'">{{ topic.title }}</td></tr>
			{% endfor %}
		{% endif %}
                </table>
            </td>

            <td>
                <table class="light">
                <tr class="doc"><td>
                    <p>
			            {{ doc.content|safe }}
		            </p>
		            <p><a href="http://en.wikipedia.org/wiki/{{ doc.title }}">Full article&nbsp;&#x25B8;</a></p>
                </td></tr>
                </table>
            </td>
        </tr></table>
    </div>

    <div id="footer">
        <br>
        <hr noshade>
    </div>
<p align=center>The contents of the Wikipedia articles are released under <a href="http://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>.</p>
</body>
</html>

BasicBrowser/templates/nav_bar.html
<div id="navigation">
<hr noshade>
<table><tr>
    <td class="navtext">Browse&nbsp;&#x25B8;</td>
        <td class="linked"><a>Topics</a>
          <ul>
            <li><a href="/topic_presence">Relative Presence</a></li>
            <li><a href="/topic/random">Random Topic</a></li>
          </ul>
        </td>
        <td class="linked"><a>Documents</a>
          <ul>
            <li><a href="/doc/random">Random Document</a></li>
          </ul>
        </td>
        <td class="linked"><a>Terms</a>
          <ul>
            <li><a href="/term/random">Random Term</a></li>
           </ul>
        </td>
        <td class="linked"><a>About</a>
          <ul>
            <li><a href="/stats">Stats</a></li>
          </ul>
        </td>
    </td>
    <td></td>
</tr></table>
</div>

BasicBrowser/templates/settings.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/pie.js"></script>
    <script language="JavaScript" src="/static/js/search.js"></script>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <title>Settings</title>

    <link href="/static/css/styling.css" rel="stylesheet" type="text/css">
</head>

<body>
{{ nav_bar|safe }}

    <div id="top"></div>

    <h1 id="header">
        <table><tr>
            <td id="title">Wikipedia Online LDA Settings</td>
        </tr></table>

        <hr noshade>
    </h1>

    <div id="main">
        <table>
            <form action="/settings/apply" method="post">
                {% csrf_token %} 
                <label for="id_doc_topic_score_threshold">Doc-Topic score threshold</label>
                  <input type="text" name="doc_topic_score_threshold" id="id_doc_topic_score_threshold" value="{{ settings.doc_topic_score_threshold }}" />
                <br />
                <input type="checkbox" name="doc_topic_scaled_score" id="id_doc_topic_scaled_score" {% if settings.doc_topic_scaled_score %}checked="yes" {% endif %}/>
                  <label for="id_doc_topic_scaled_score">Use threshold in proportion to document size</label>
                <br />
                <input type="submit" value="Apply" />
            </form>
        </table>
    </div>

    <div id="footer">
        <br>
        <hr noshade>
    </div>
</body>
</html>

BasicBrowser/templates/stats.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/pie.js"></script>
    <script language="JavaScript" src="/static/js/search.js"></script>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <title>Stats</title>

    <link href="/static/css/styling.css" rel="stylesheet" type="text/css">
</head>

<body>
{{ nav_bar|safe }}

    <div id="top"></div>

    <h1 id="header">
        <table><tr>
            <td id="title">Wikipedia Online LDA Stats</td>
        </tr></table>

        <hr noshade>
    </h1>

    <div id="main">
        <table>
            <tr><td width="210px">
            Model started running at {{ start_time }}, and has run {{ start_time|timesince:last_update }}.
            <br>Last update at {{ last_update }}, or {{ last_update|timesince}} ago.
            <br>{{ num_batches }} Batches Completed
            <br>{{ num_docs }} Documents
            <br>{{ num_topics }} Topics
            <br>{{ num_terms }} Terms
            </td></tr>
        </table>
    </div>

    <div id="footer">
        <br>
        <hr noshade>
    </div>
</body>
</html>

BasicBrowser/templates/term.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/jquery.rightClick.js"></script>
    
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>{{ term.title }}</title>
<link href="/static/css/styling.css" rel="stylesheet" type="text/css">

</head>
  <body>
{{ nav_bar|safe }}
<div id="top"></div>
<h1 id="header">
<table><tr>
<td id="title">{{ term.title }}</td>
</tr></table></span>
<hr noshade>
</h1>

<div id="graph"> 
<table width="100%">
{% for topic, topic_score, width in topic_tuples %}
<tr><td><table width="{{ width|floatformat:1 }}%" ><tr><td class="high-contrast" title="{{ topic_score|floatformat:0 }}" onclick="window.location.href='/topic/{{ topic.id }}'">{{ topic.title }}</td></tr></table></td></tr>
{% endfor %}
</table> 
</div>

<div id="footer">
<br>
<hr noshade>
</div>
  </body>
</html>

BasicBrowser/templates/term_list.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/jquery.rightClick.js"></script>
    <script language="JavaScript" src="../js/bottom_bar_chart.js"></script> 
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>Wikipedia Topics</title>
<link href="/static/css/styling.css" rel="stylesheet" type="text/css">

</head>
  <body>
{{ nav_bar|safe }}
<div id="top"></div>
<div id="header">
<h1>Wikipedia Terms</h1>
<h2>List of Terms by Frequency</h2> 
<hr noshade>
</div>
<div id="list"> 
<div ><table onmouseover="show_count_bar()" onmouseout="hide_count_bar()"> 
{% for row in rows %}
	<tr>
	{% for term, count, percent in row %}
		{% if term %}
			<td title="{{ count }}" onclick="window.location.href='/term/{{ term.id }}'" onmouseover="count_adjust({{ percent }})">{{ term.title }}</td>
		{% else %}
			<td class="blank"></td>
		{% endif %}
	{% endfor %}
	</tr>
{% endfor %} 
</table>

prev next
</div>
</div>

<div onmouseover="show_count_bar()" onmouseout="hide_count_bar()"><table class="hidden"><tr><td class="count"></td><td class="total"></td> 
</tr></table></div>

<div id="footer">
<br>
<hr noshade>
</div>
  </body>
</html>

BasicBrowser/templates/topic.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/jquery.rightClick.js"></script>
    <script type="text/JavaScript"> 
    <!--
    function highlight(id) {
	   	var list = document.getElementById(id+'_list');
	   	var bar = document.getElementById(id+'_bar');
		if (list != null) {
			list.style.backgroundColor='#628AE3';
		}
		if (bar != null) {
			bar.style.backgroundColor='#416DCC';
		}
	}
    
    function unhighlight(id) {
		var list = document.getElementById(id+'_list');
	   	var bar = document.getElementById(id+'_bar');
		if (list != null) {
			list.style.backgroundColor='#799FF2';
		}
		if (bar != null) {
			bar.style.backgroundColor='#799FF2';
		}
    }
    //-->
    </script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>{{ topic.title }}</title>
<link href="/static/css/styling.css" rel="stylesheet" type="text/css">

</head>
  <body>
{{ nav_bar|safe }}
<div id="top"></div>
<h1 id="header">
<table><tr>
<td id="title">{{ topic.title }}</td>
</tr></table></span>
<hr noshade>
</h1>

<div id="main">
<table width="100%" class="high-contrast-table"><tbody><tr>
</tr></tbody></table>
<table><tr>
<td width="30.0%">
<table class="dark">
<tr class="title">
<td>words</td></tr>
{% if terms %}
	{% for term in terms %}
	<tr class="list" onclick="window.location.href='/term/{{ term.id }}'" onmouseover="highlight('{{ term.title }}')" onmouseout="unhighlight('{{ term.title }}')"><td id="{{ term.title }}_list">{{ term.title }}</td><tr>
	{% endfor %}
{% endif %}
<tmv-topic-terms-column>
</table>
</td>

<td width="70.0%">
<table class="light">
<tr class="title">
<td>related documents</td>
</tr>
{% if docs %}
	{% for doc in docs %}
	<tr class="list"><td id="{{ doc.title }}" onclick="window.location.href='/doc/{{ doc.id }}'">{{ doc.title }}</td><tr>
	{% endfor %}
{% endif %}
</table>
</td>

</tr></table>
</div>

<div id="footer">
<br>
<hr noshade>
</div>
  </body>
</html>

BasicBrowser/templates/topic_list.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/jquery.rightClick.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>Wikipedia Topics</title>
<link href="/static/css/styling.css" rel="stylesheet" type="text/css">

</head>
  <body>
{{ nav_bar|safe }}
<div id="top"></div>
<div id="header">
<h1>Wikipedia Topics</h1>
<h2>List of Terms Per Topic</h2> 
<hr noshade>
</div>
<div id="topics"> 
	<table>	
	{% for row in rows %}
		<tr class="titles"> 
		{% for topic in row.0 %}
			{% if topic %}
				<td onclick="window.location.href='/topic/{{ topic.id }}'">{{ topic.title }}</td>
			{% else %}
				<td class="blank"></td>
			{% endif %}
		{% endfor %}
		</tr>
		{% for terms in row.1%}
		<tr>
			{% for term in terms %}
				{% if term %}
					<td onclick="window.location.href='/term/{{ term.id }}'">{{ term.title }}</td>
				{% else %}
					<td class="blank"></td>
				{% endif %}
			{% endfor %}
		</tr>
		{% endfor %}
		</tr><tr class="spacer"><td></td><td></td><td></td><tr> 
	{% endfor %}
	</table>
	 
</div>

<div id="footer">
<br>
<hr noshade>
</div>
  </body>
</html>

BasicBrowser/templates/topic_presence.html
<html>
<head>
    <script language="JavaScript" src="http://code.jquery.com/jquery-1.4.4.js"></script>
    <script language="JavaScript" src="/static/js/jquery.rightClick.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>Wikipedia Topics</title>
<link href="/static/css/styling.css" rel="stylesheet" type="text/css">

</head>
  <body>
{{ nav_bar|safe }}
<div id="top"></div>
<div id="header">
<h1>Wikipedia Topics</h1>
<h2>Relative Presence of Topics in all Documents</h2> 
<hr noshade>
</div>
<div id="graph"> 
<table width="100%">
{% for topic, topic_score, width in topic_tuples %}
<tr><td><table width="{{ width|floatformat:1 }}%" ><tr><td class="high-contrast" title="{{ topic_score|floatformat:0 }}" onclick="window.location.href='/topic/{{ topic.id }}'">{{ topic.title }}</td></tr></table></td></tr>
{% endfor %}
</table> 
</div>

<div id="footer">
<br>
<hr noshade>
</div>
  </body>
</html>